// Code generated by protoc-gen-vtobj. Please DO NOT EDIT.

package manager

// AddItem appends a new SubsystemStatus object to the existing list of items within the existing SubsystemStatusList.
func (a *SubsystemStatusList) AddItem(item *SubsystemStatus) {
	a.Items = append(a.Items, item)
}

// AddItem appends a new BuildInfo object to the existing list of items within the existing BuildInfoList.
func (a *BuildInfoList) AddItem(item *BuildInfo) {
	a.Items = append(a.Items, item)
}
