// Code generated by protoc-gen-vtobj. Please DO NOT EDIT.

package manager

// AddItem appends a new SubsystemStatus object to the existing list of items within the existing SubsystemStatusList.
func (vt *SubsystemStatusList) AddItem(item *SubsystemStatus) {
	vt.Items = append(vt.Items, item)
}

// AddItem appends a new BuildInfo object to the existing list of items within the existing BuildInfoList.
func (vt *BuildInfoList) AddItem(item *BuildInfo) {
	vt.Items = append(vt.Items, item)
}
