/*
*	Copyright (C) 2025 Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: otel_list.proto

package otel

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SamplerStatusList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*SamplerStatus `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *SamplerStatusList) Reset() {
	*x = SamplerStatusList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otel_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SamplerStatusList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplerStatusList) ProtoMessage() {}

func (x *SamplerStatusList) ProtoReflect() protoreflect.Message {
	mi := &file_otel_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplerStatusList.ProtoReflect.Descriptor instead.
func (*SamplerStatusList) Descriptor() ([]byte, []int) {
	return file_otel_list_proto_rawDescGZIP(), []int{0}
}

func (x *SamplerStatusList) GetItems() []*SamplerStatus {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_otel_list_proto protoreflect.FileDescriptor

var file_otel_list_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6f, 0x74, 0x65, 0x6c, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x6f, 0x74, 0x65, 0x6c, 0x1a, 0x0a, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x11, 0x53, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x29, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x6f, 0x74, 0x65, 0x6c, 0x2e, 0x53,
	0x61, 0x6d, 0x70, 0x6c, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2e, 0x2f, 0x6f, 0x74, 0x65, 0x6c, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_otel_list_proto_rawDescOnce sync.Once
	file_otel_list_proto_rawDescData = file_otel_list_proto_rawDesc
)

func file_otel_list_proto_rawDescGZIP() []byte {
	file_otel_list_proto_rawDescOnce.Do(func() {
		file_otel_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_otel_list_proto_rawDescData)
	})
	return file_otel_list_proto_rawDescData
}

var (
	file_otel_list_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
	file_otel_list_proto_goTypes  = []interface{}{
		(*SamplerStatusList)(nil), // 0: otel.SamplerStatusList
		(*SamplerStatus)(nil),     // 1: otel.SamplerStatus
	}
)

var file_otel_list_proto_depIdxs = []int32{
	1, // 0: otel.SamplerStatusList.items:type_name -> otel.SamplerStatus
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_otel_list_proto_init() }
func file_otel_list_proto_init() {
	if File_otel_list_proto != nil {
		return
	}
	file_otel_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_otel_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SamplerStatusList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_otel_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_otel_list_proto_goTypes,
		DependencyIndexes: file_otel_list_proto_depIdxs,
		MessageInfos:      file_otel_list_proto_msgTypes,
	}.Build()
	File_otel_list_proto = out.File
	file_otel_list_proto_rawDesc = nil
	file_otel_list_proto_goTypes = nil
	file_otel_list_proto_depIdxs = nil
}
