// Code generated by protoc-gen-vtobj. Please DO NOT EDIT.

package otel

// AddItem appends a new SamplerStatus object to the existing list of items within the existing SamplerStatusList.
func (vt *SamplerStatusList) AddItem(item *SamplerStatus) {
	vt.Items = append(vt.Items, item)
}
