/*
*	Copyright (C) 2023 Kendall Tauser
*
*	This program is free software; you can redistribute it and/or modify
*	it under the terms of the GNU General Public License as published by
*	the Free Software Foundation; either version 2 of the License, or
*	(at your option) any later version.
*
*	This program is distributed in the hope that it will be useful,
*	but WITHOUT ANY WARRANTY; without even the implied warranty of
*	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*	GNU General Public License for more details.
*
*	You should have received a copy of the GNU General Public License along
*	with this program; if not, write to the Free Software Foundation, Inc.,
*	51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 */

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: generictypes.proto

package serialization

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenericErrorResponse
//
// GenericErrorResponse is a generic error object that is returned whenever an API
// endpoint returns an unexpected error.
//
// This model will be sent with any invalid request, but will be
// tailored to the specific error.
//
// swagger:model GenericErrorResponse
type GenericErrorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The http error string for this error.
	//
	// required: true
	// @gotags: yaml:"error" xml:"error" bson:"error"
	Error string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty" yaml:"error" xml:"error" bson:"error"`
	// A more verbose description of this error, sometimes with a subsystem reference.
	//
	// required: true
	// @gotags: yaml:"description" xml:"description" bson:"description"
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty" yaml:"description" xml:"description" bson:"description"`
	// The integer http status code corresponding to error string.
	//
	// required: true
	// @gotags: yaml:"code" xml:"code" bson:"code"
	Code uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty" yaml:"code" xml:"code" bson:"code"`
	// The timestamp of this response being returned.
	//
	// required: true
	// @gotags: yaml:"timestamp" xml:"timestamp" bson:"timestamp"
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp" xml:"timestamp" bson:"timestamp"`
}

func (x *GenericErrorResponse) Reset() {
	*x = GenericErrorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generictypes_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GenericErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenericErrorResponse) ProtoMessage() {}

func (x *GenericErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generictypes_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenericErrorResponse.ProtoReflect.Descriptor instead.
func (*GenericErrorResponse) Descriptor() ([]byte, []int) {
	return file_generictypes_proto_rawDescGZIP(), []int{0}
}

func (x *GenericErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *GenericErrorResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GenericErrorResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GenericErrorResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

// OKResponse
//
// OKResponse is a generic response returned whenever an operation was successful.
//
// swagger:model OKResponse
type OKResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Human-readable message for the successful response.
	//
	// required: true
	// @gotags: yaml:"message" xml:"message" bson:"message"
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty" yaml:"message" xml:"message" bson:"message"`
	// The timestamp of this response being returned.
	//
	// required: true
	// @gotags: yaml:"timestamp" xml:"timestamp" bson:"timestamp"
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty" yaml:"timestamp" xml:"timestamp" bson:"timestamp"`
	// The integer http status code corresponding to the response.
	//
	// required: true
	// @gotags: yaml:"code" xml:"code" bson:"code"
	Code uint32 `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty" yaml:"code" xml:"code" bson:"code"`
}

func (x *OKResponse) Reset() {
	*x = OKResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generictypes_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OKResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OKResponse) ProtoMessage() {}

func (x *OKResponse) ProtoReflect() protoreflect.Message {
	mi := &file_generictypes_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OKResponse.ProtoReflect.Descriptor instead.
func (*OKResponse) Descriptor() ([]byte, []int) {
	return file_generictypes_proto_rawDescGZIP(), []int{1}
}

func (x *OKResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OKResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *OKResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type VTTime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VTTime) Reset() {
	*x = VTTime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_generictypes_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VTTime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VTTime) ProtoMessage() {}

func (x *VTTime) ProtoReflect() protoreflect.Message {
	mi := &file_generictypes_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VTTime.ProtoReflect.Descriptor instead.
func (*VTTime) Descriptor() ([]byte, []int) {
	return file_generictypes_proto_rawDescGZIP(), []int{2}
}

var File_generictypes_proto protoreflect.FileDescriptor

var file_generictypes_proto_rawDesc = []byte{
	0x0a, 0x12, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x61, 0x70, 0x69, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x9c, 0x01, 0x0a, 0x14, 0x47, 0x65, 0x6e, 0x65, 0x72, 0x69, 0x63, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x22, 0x74,
	0x0a, 0x0a, 0x4f, 0x4b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65,
	0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x08, 0x0a, 0x06, 0x56, 0x54, 0x54, 0x69, 0x6d, 0x65, 0x42, 0x12,
	0x5a, 0x10, 0x2e, 0x2e, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_generictypes_proto_rawDescOnce sync.Once
	file_generictypes_proto_rawDescData = file_generictypes_proto_rawDesc
)

func file_generictypes_proto_rawDescGZIP() []byte {
	file_generictypes_proto_rawDescOnce.Do(func() {
		file_generictypes_proto_rawDescData = protoimpl.X.CompressGZIP(file_generictypes_proto_rawDescData)
	})
	return file_generictypes_proto_rawDescData
}

var file_generictypes_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_generictypes_proto_goTypes = []interface{}{
	(*GenericErrorResponse)(nil),  // 0: apitypes.GenericErrorResponse
	(*OKResponse)(nil),            // 1: apitypes.OKResponse
	(*VTTime)(nil),                // 2: apitypes.VTTime
	(*timestamppb.Timestamp)(nil), // 3: google.protobuf.Timestamp
}
var file_generictypes_proto_depIdxs = []int32{
	3, // 0: apitypes.GenericErrorResponse.timestamp:type_name -> google.protobuf.Timestamp
	3, // 1: apitypes.OKResponse.timestamp:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_generictypes_proto_init() }
func file_generictypes_proto_init() {
	if File_generictypes_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_generictypes_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GenericErrorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generictypes_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OKResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_generictypes_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VTTime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_generictypes_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_generictypes_proto_goTypes,
		DependencyIndexes: file_generictypes_proto_depIdxs,
		MessageInfos:      file_generictypes_proto_msgTypes,
	}.Build()
	File_generictypes_proto = out.File
	file_generictypes_proto_rawDesc = nil
	file_generictypes_proto_goTypes = nil
	file_generictypes_proto_depIdxs = nil
}
